FROM bcbio/bcbio:latest

RUN locale-gen en_US.UTF-8

RUN /usr/local/bin/bcbio_conda remove --force --yes bcbio-nextgen

ADD ./ /bcbio-nextgen

ENV PATH /usr/local/share/bcbio-nextgen/anaconda/bin:$PATH


# Add the dependencies to requirements!!! 
RUN conda install multiqc-bcbio=0.1.6 goleft=0.1.6 tophat-recondition=1.4 -c bioconda --yes

WORKDIR /bcbio-nextgen

RUN pip install -qe . 
RUN pip install -qr requirements_dev.txt
