# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, :path => "bootstrap.sh", :privileged => false

  config.vm.network :forwarded_port, guest: 8090, host: 8090
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Configure virtualbox
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    # vb.customize ["modifyvm", :id, "--cpus", "4"]
  end
end
